EXPORT_FUNC(get_version)
EXPORT_FUNC(getc)
EXPORT_FUNC(tstc)
EXPORT_FUNC(putc)
EXPORT_FUNC(puts)
EXPORT_FUNC(printf)
EXPORT_FUNC(install_hdlr)
EXPORT_FUNC(free_hdlr)
EXPORT_FUNC(malloc)
EXPORT_FUNC(free)
EXPORT_FUNC(udelay)
EXPORT_FUNC(get_timer)
EXPORT_FUNC(vprintf)
EXPORT_FUNC(do_reset)
#if (CONFIG_COMMANDS & CFG_CMD_I2C)
EXPORT_FUNC(i2c_write)
EXPORT_FUNC(i2c_read)
#endif	/* CFG_CMD_I2C */
#if defined(CONFIG_BQ27541)
EXPORT_FUNC(bq27541_capacity)
EXPORT_FUNC(bq27541_temperature)
EXPORT_FUNC(bq27541_voltage)
EXPORT_FUNC(bq27541_current)
EXPORT_FUNC(bq27541_flags)
EXPORT_FUNC(bq27541_type)
#endif
#if defined(CONFIG_SMB347)
EXPORT_FUNC(smb347_aicl_current)
EXPORT_FUNC(smb347_apsd_result)
EXPORT_FUNC(smb347_charging_current)
EXPORT_FUNC(smb347_config_enable)
EXPORT_FUNC(smb347_redo_apsd)
#endif
